---

- hosts: linux
  become: true
  tasks:

  - name: update repository index
    apt: 
      update_cache: yes
      state: latest

  - name: install tmux package
    apt:
      name: tmux
      state: latest
